//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppInvoiceTaks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public tblCustomer()
        {
            this.tblInvoiceDetails = new HashSet<tblInvoiceDetail>();
        }
    
        public int customerId { get; set; }
        public string customerName { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
    
        public virtual ICollection<tblInvoiceDetail> tblInvoiceDetails { get; set; }
    }
}
