//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppInvoiceTaks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoiceDetail
    {
        public tblInvoiceDetail()
        {
            this.tblInviocePayments = new HashSet<tblInviocePayment>();
            this.tblInvoiceItems = new HashSet<tblInvoiceItem>();
        }
    
        public int invoiceId { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<System.DateTime> invoiceDate { get; set; }
        public Nullable<int> totalAmount { get; set; }
        public string status { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual ICollection<tblInviocePayment> tblInviocePayments { get; set; }
        public virtual ICollection<tblInvoiceItem> tblInvoiceItems { get; set; }
    }
}
