//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppInvoiceTaks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItem
    {
        public tblItem()
        {
            this.tblInvoiceItems = new HashSet<tblInvoiceItem>();
        }
    
        public int itemId { get; set; }
        public string itemName { get; set; }
        public Nullable<double> itemRate { get; set; }
        public Nullable<int> itemTax { get; set; }
    
        public virtual ICollection<tblInvoiceItem> tblInvoiceItems { get; set; }
    }
}
