//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppInvoiceTaks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoiceItem
    {
        public int invoiceItemId { get; set; }
        public Nullable<int> invoiceId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> itemId { get; set; }
    
        public virtual tblInvoiceDetail tblInvoiceDetail { get; set; }
        public virtual tblItem tblItem { get; set; }
    }
}
